### ISSUE TITLE
To-do list for the app

### ISSUE THREAD

**Issue by Zingo21** [Zingo21/Strog_Planner#1]
- [ ] Make a booking page
- [ ] Make a login page
- [ ] Look up for how to save all bookings and accounts on some database on google
- [ ] Make a friends list page
- [ ] Make it possible to get notifications
